----DDL statement for Hotel Management System

use master
go
drop database if exists HotelManagementSystem
go
--------create database 
begin try
create database HotelManagementSystem
end try
begin catch
print error_message()
end catch
go
-----------create login for HotelManagementSystem with password
begin try
create login HotelAdmin with password = '123123',default_database= HotelManagementSystem
end try
begin catch
print error_message()
end catch
go

----begin try
----alter login HotelAdmin with default_database= HotelManagementSystem,
----default_language= English 
----end try
----begin catch
----print error_message()
----end catch
----go
------------ assign server role

begin try
create server role ServerAdmin
alter server role ServerAdmin add member HotelAdmin
end try
begin catch
print error_message()
end catch
go
-------------use HotelManagementSystem

use HotelManagementSystem
go

---------- create database role for hotel application
create role HotelEmployeeRole
go

--------- assigning database role
alter role db_owner add member HotelEmployeeRole
go
----------create schema 

create schema HotelSystem
go
----------grant permissions to role on schema

grant select,insert,update,delete, execute 
on schema :: HotelSystem to HotelEmployeeRole
go

---- create database user for login

create user HotelAdminuser for login HotelAdmin
with default_schema = HotelSystem
go

alter role HotelEmployeeRole
add member HotelAdminuser
go

----1----Guest table-------
create table Guest
(
GuestId int identity primary key ,
GuestName varchar(50),
Email varchar(50),
Phone varchar(50),
Member tinyint,
Address varchar(50)
)
go

--(2a)--RoomTypename table----
create table RoomType
(
TypeId int identity primary key,
TypeName varchar(50)not null,
Ratepernight money,
Descriptions varchar (100)
)
 go

 --2---room information table-
create table Room
(
RoomId int identity primary key,
RoomNumber varchar (10) not null unique ,
TypeId int references RoomType (TypeId),
Status varchar(50) not null default 'available'check (status in ('available', 'booked'))
)
 go

  ---3(a)--- table facility
create table Facility
(
FacilityId int identity primary key,
Facilityname varchar (50),
Facilitycost decimal (10,2)
)
go

 --3--booking information table-----
create table Booking
(
BookingId int identity primary key,
GuestId int references Guest (GuestId)on delete cascade on update cascade,
RoomId int references Room(RoomId)on delete cascade on update cascade,
BookingDate date not null,
Check_in date null,
Check_out date null,
Stayingdays tinyint ,
Bookingstatus varchar(50) not null default 'active',
Cancelleddate date null
 )
go

-------trigger to auto generate date in booking table--

create trigger tr_autogeneratedate
on booking
after insert,update
as
begin
set nocount on
 --------- For active bookings
update b
set check_in = i.check_in,
check_out = case when i.Check_in is not null and i.Stayingdays is not null then  dateadd(day,i.stayingdays,i.check_in)else null end,
cancelleddate =  null 
from booking as b
inner join inserted as i 
on b.BookingId= i.BookingId
where i.bookingstatus= 'active'
-- ---------------For cancelled bookings
update b
set check_in = null,
check_out = null,
Cancelleddate = dateadd(day, 2, i.BookingDate) 
from booking as b
inner join inserted as i 
on b.BookingId= i.BookingId
where i.bookingstatus= 'cancelled'
end
go

----4(a)-table for paymentmethod----

create table paymenttype
(
Paytypeid int identity primary key ,
Paytype varchar (20)not null
)
go

-----4--payment ---
create table Payment
(
PaymentId int identity primary key,
paytypeid int references paymenttype(paytypeid),
BookingId int references Booking(BookingId)on delete cascade on update cascade,
FacilityId int references facility(facilityId),
Servicecharge decimal(10,2),
AmountTotal decimal (10,2),
PaymentDate date
)
go

----- create trigger to automatically calculate amountTotal in payment table
create trigger tr_calculateamounttotal
on Payment
after insert
as
begin
set nocount on
---------------------------formula(Ratepernight * Stayingdays) + FacilityCost + ServiceCharge
update p
set AmountTotal = (rt.Ratepernight * b.stayingdays) + f.facilityCost + p.servicecharge,
 PaymentDate = b.Check_out
from Payment p
inner join Booking b on p.BookingId = b.BookingId
inner join Room r on b.RoomId = r.RoomId
inner join RoomType rt on r.TypeId = rt.TypeId
inner join Facility f on p.facilityId = f.FacilityId
inner join inserted i on p.paymentId = i.paymentId
end
go

-----5----booking cancalled table
 create table Cancelled
 (
 Cancelid int identity primary key nonclustered,
 Bookingid int references booking(bookingid),
 Cancelleddate date
 )
 go

 -----6----Users table
create table Users
(
UserId int identity primary key,
UserName varchar(50) not null,
Password nvarchar(50) not null
)

---7 work position table
create table position
(
PositionId int identity primary key,
PositionName varchar(50) not null
--BasicSalary money not null
)

---8--staf table
create table Staff
(
StaffId int identity primary key,
StaffName varchar(50) not null,
Contact nvarchar(50) not null,
PositionId int references position(PositionId),
ShiftTime nvarchar(50) not null,
BasicSalary money not null,
Allowances money not null,
ProvidentFund as (BasicSalary * 0.10),
TotalSalary as (BasicSalary + Allowances - (BasicSalary * 0.10))
)

 ----clustered index--
create clustered index ix_cancelled on cancelled(cancelid)
go
--create nonclusterd index--
create nonclustered index ix_guest on guest(GuestName)
go
 -----create Stored Procedure to insert a new guest

create procedure sp_addguest 
@GuestName varchar(50),
@Email varchar(50),
@Phone varchar(50),
@Member int,
@Address varchar(50)
as
begin
insert into guest (GuestName, Email, Phone, Member, Address)
values (@GuestName, @Email, @Phone, @Member, @Address)
end
go

 -----create Stored Procedure with return

create procedure sp_addguest_return 
@GuestName varchar(50),
@Email varchar(50),
@Phone varchar(50),
@Member int,
@Address varchar(50)
as
begin
begin try
insert into guest (GuestName, Email, Phone, Member, Address)
values (@GuestName, @Email, @Phone, @Member, @Address)
return 1
end try
begin catch
Return 0
end catch
end
go

-----create Stored Procedure with output parameter

create procedure sp_getguestbookingcount
    @GuestName varchar(50),
    @Bookingcount int output
as
begin
    -- Assign the booking count for the guest into the output parameter
    select @Bookingcount = count(*)
    from Booking B
    inner join Guest g on b.GuestID = g.GuestID
    where g.GuestName = @GuestName
end
go

-----create Stored Procedure with transaction

create procedure sp_addpayment_Hotel
@paymentid int,
@Amountpaid money
as
begin
begin try
begin tran
-- Insert payment
insert into Payment (PaymentId, Amounttotal, PaymentDate)
values (@PaymentId, @Amountpaid, getdate())
commit tran
end try
begin catch
rollback tran
print 'Error: Could not complete the payment.'
end catch
end
go

---- scalar-Valued Function

create function fn_getallbookingsbyguest
(
@GuestName varchar(50)
)
returns int
as
begin
declare @allbookings int
select @allbookings = count(*)
from Booking as b
inner join Guest as g on b.Guestid = g.Guestid
where g.GuestName = @GuestName
if @allbookings is null
set @allBookings = 0
return @allBookings
end
go

------ Table-Valued Function
create function fn_getbooking2
(@guestid int)
returns table
as 
return
(select bookingid,bookingdate,roomid,check_in
from booking
where guestid= @guestid )
go

-------- muulti-Valued Function

create function fn_GetBookings3
(
@GuestName varchar(50)
)
returns @Bookings table
(
Bookingid int,Roomid int,Check_in date,Check_out date
)
as
begin
insert into @Bookings
select b.Bookingid,b.Roomid,b.Check_in,b.Check_out
from Booking b
inner join Guest g on b.Guestid = g.Guestid
where g.GuestName = @GuestName
return
end 
go



print 'complete DDL'